micronaut.application.name=address-book
micronaut.server.port=8080

datasources.default.url=jdbc:h2:mem:addressbook;DB_CLOSE_DELAY=-1
datasources.default.driver-class-name=org.h2.Driver
datasources.default.username=sa
datasources.default.password=

jpa.default.packages-to-scan[0]=micronaut.tutorial.addressbook.entity
jpa.default.properties.hibernate.hbm2ddl.auto=create
jpa.default.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
