micronaut.application.name=order
micronaut.server.port=8081

datasources.default.url=jdbc:h2:mem:orderdb;DB_CLOSE_DELAY=-1
datasources.default.driver-class-name=org.h2.Driver
datasources.default.username=sa
datasources.default.password=

jpa.default.packages-to-scan[0]=micronaut.order.entity
jpa.default.properties.hibernate.hbm2ddl.auto=create
jpa.default.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
