micronaut.application.name=jaxrs-customer
micronaut.server.port=8080
micronaut.server.context-path=/webapi

datasources.default.url=jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1
datasources.default.driver-class-name=org.h2.Driver
datasources.default.username=sa
datasources.default.password=

jpa.default.packages-to-scan[0]=micronaut.tutorial.customer.data
jpa.default.properties.hibernate.hbm2ddl.auto=create
jpa.default.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
