quarkus.rest.path=/api

# Database configuration — PostgreSQL for all profiles.
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/realworld
quarkus.datasource.username=realworld
quarkus.datasource.password=realworld
quarkus.hibernate-orm.database.generation=drop-and-create

# JWT settings
smallrye.jwt.sign.key.location=classpath:privateKey.pem
mp.jwt.verify.publickey.location=classpath:publicKey.pem
mp.jwt.verify.issuer=users-service
